openapi: 3.0.1

info:
  title: {{ cookiecutter.app_name }} API
  description: {{ cookiecutter.app_description }}
  version: 1.0.0

paths:
  /hello:
    get:
      description: hello world
      responses:
        "200":
          description: hello world response
          content:
            application/json+hal:
              schema:
                type: object
                properties:
                  msg:
                    type: string
        "default":
          $ref: '#/components/responses/error'

components:
  responses:
    error:
      description: Error. Details in response.
      content:
        application/json+hal:
          schema:
            $ref: '#/components/schemas/error_response'

  schemas:
    error_response:
      description: An error response
      type: object
      required:
        - error_name
        - error_description
      properties:
        error_name:
          description: Name of the error
          type: string
        error_description:
          description: A short description of the possible causes of the error
          type: string

    hal_self_link:
      type: object
      required:
        - _links
      properties:
        _links:
          type: object
          required:
            - self
          properties:
            self:
              allOf:
                - description: a link pointing to the containing resource
                - $ref: "#/components/schemas/hal_link"
                - example:
                    href: "/self/this"

    hal_nav_links:
      type: object
      properties:
        _links:
          type: object
          properties:
            prev:
              allOf:
                - description: navigate to previous page of paginated resource list
                - $ref: "#/components/schemas/hal_link"
                - example:
                    href: "/self/prev"
            next:
              allOf:
                - description: navigate to next page of paginated resource list
                - $ref: "#/components/schemas/hal_link"
                - example:
                    href: "/self/next"

    hal_link:
      type: object
      required:
        - href
      properties:
        href:
          type: string
        templated:
          type: boolean
      additionalProperties:
        type: string
